import type {
  IEducationAndHobbies,
  IMyFullProjects,
  IMyMiniProjects,
  ISkill,
  ISocial,
} from "./types";

export const mySkills: ISkill[] = [
  { id: 1, name: "Html5", icon: "skills/html.svg" },
  { id: 2, name: "Css3", icon: "skills/css.svg" },
  { id: 3, name: "Scss", icon: "skills/scss.svg" },
  { id: 4, name: "Js", icon: "skills/js.svg" },
  { id: 5, name: "Ts", icon: "skills/ts.svg" },
  { id: 6, name: "React", icon: "skills/react.svg" },
  { id: 7, name: "Next", icon: "skills/next.svg" },
  { id: 8, name: "Redux", icon: "skills/redux.svg" },
  { id: 9, name: "Zustand", icon: "skills/zustand.svg" },
  { id: 10, name: "Tanstack", icon: "skills/tanstack.svg" },
  { id: 11, name: "Swr", icon: "skills/swr.svg" },
  { id: 12, name: "Axios", icon: "skills/axios.svg" },
  { id: 13, name: "Prisma", icon: "skills/prisma.svg" },
  { id: 14, name: "Convex", icon: "skills/convex.svg" },
  { id: 15, name: "Supabase", icon: "skills/supabase.svg" },
  { id: 16, name: "Tailwind", icon: "skills/tailwind.svg" },
  { id: 17, name: "ShadCn", icon: "skills/shadcn.svg" },
  { id: 18, name: "ChakraUi", icon: "skills/chakra.svg" },
  { id: 19, name: "Figma", icon: "skills/figma.svg" },
  { id: 20, name: "GitHub", icon: "skills/github.svg" },
];

export const myMiniProjects: IMyMiniProjects[] = [
  {
    id: 1,
    title: "Nikey",
    description: "Интернет магазин кроссовок",
    link: "/nikey",
  },
  {
    id: 2,
    title: "Drivich-V2",
    description: "Перекупы автомобилей Porsche",
    link: "/drivich",
  },
  {
    id: 3,
    title: "Eternal Abyss",
    description: "Cайт музыкльной метал группы",
    link: "/eternal",
  },
  {
    id: 4,
    title: "Grind Guitar",
    description: "Трекер гитарных практик",
    link: "/grind",
  },
];

export const educationAndHobbies: IEducationAndHobbies[] = [
  {
    id: 1,
    name: "Образование",
    text: "Прошёл множество курсов по веб-разработке, имею сертификаты. Постоянно повышаю квалификацию, изучаю новые инструменты, совершенствую навыки и применяю знания на практике, чтобы оставаться в актуальном контексте индустрии.",
    image: "1.jpg",
    certificates: [
      {
        name: "JavaScript",
        link: "https://ude.my/UC-ff690d4a-1d82-4fd4-befc-61b065243886/",
      },
      {
        name: "React",
        link: "https://ude.my/UC-8827e5b8-e060-48bc-902b-14aa624cdece/",
      },
      {
        name: "React",
        link: "https://ude.my/UC-74972f28-9733-4972-ac0a-b278b329fad7/",
      },
      {
        name: "UI/UX Design",
        link: "https://ude.my/UC-1dd31f29-0f11-4d1c-a287-16f321333919/",
      },
    ],
  },
  {
    id: 2,
    name: "Опыт разработки",
    text: "За прошлый год я создал несколько pet-проектов — от простой вёрстки до полноценных full-stack-приложений. Самостоятельно работал над дизайном, улучшал код и производительность, исправлял ошибки и внедрял новые функции. Этот опыт научил меня находить решения и доводить идеи до результата.",
    image: "2.jpg",
  },
  {
    id: 3,
    name: "Увлечения",
    text: "Развиваюсь в веб-разработке и музыке. Несколько лет занимался акустической гитарой, сейчас уже полгода играю на электрогитаре: изучаю рифы, создаю что-то своё. Творческий человек, раньше интересовался дизайном и интерфейсами. Люблю активный отдых и рыбалку.",
    image: "3.jpg",
  },
];

export const mySocial: ISocial[] = [
  {
    id: 1,
    name: "github",
    icon: "github.svg",
    href: "https://github.com/Bodich26",
  },
  {
    id: 2,
    name: "telegram",
    icon: "telegram.svg",
    href: "https://t.me/bodich12",
  },
  {
    id: 3,
    name: "Mail",
    icon: "mail.svg",
    href: "mailto:4634815@gmail.com",
  },
];

export const myFullProjects: IMyFullProjects[] = [
  {
    id: 1,
    title: "Nikey",
    subtitle: "Интернет магазин кроссовок",
    idea: "бъединить коммерческий e-commerce функционал с бренд-медиа: создать платформу, где покупка обуви совмещена с новостями о релизах, историей бренда и актуальными скидками.",
    implementation: [
      "E-Commerce & Вариативность: каталог с фильтрацией, детальные карточки товаров с выбором размера/цвета и поддержка модификаций моделей.",
      "Гибкий Guest Checkout: покупка доступна как зарегистрированным пользователям, так и гостям (через временные сессионные токены).",
      "Процесс покупки и фидбек: полноценное оформление, списки избранного и система отзывов/комментариев к товарам.",
      "Бренд-Медиа секции: главная страница с блоками популярных моделей (по просмотрам), новостным разделом и релизными галереями.",
      "Full-Stack & UI/UX: проектирование архитектуры клиент-серверного взаимодействия и самостоятельный дизайн интерфейса с нуля.",
    ],
    frontend: [
      "Next",
      "Ts",
      "Nuqs",
      "RTK",
      "React Hook Form",
      "Zod",
      "Tailwind",
      "Swiper",
      "Lucide Icon",
      "Flowbite UI",
      "FSD Архитектура Проекта",
    ],
    backend: ["Clerk", "Prisma", "Ngrok", "Svix", "Rest API"],
    githubUrl: "https://github.com/Bodich26/next-nikey",
    liveUrl: "https://next-nikey.vercel.app/",
    screenshots: [
      "projects/nikey/1.jpg",
      "projects/nikey/2.jpg",
      "projects/nikey/3.jpg",
      "projects/nikey/4.jpg",
    ],
  },
  {
    id: 2,
    title: "Drivich-V2",
    subtitle: "Перекупы автомобилей Porsche",
    idea: "Переработанная версия автосалона с упором на чистую архитектуру и пользовательский опыт. Проект воспроизводит полный цикл e-commerce: от поиска автомобиля в каталоге до оформления заказа и отслеживания его статуса в личном кабинете.",
    implementation: [
      "E-Commerce функционал: интерактивный каталог авто с фильтрацией, детальные страницы моделей, корзина и список избранного.",
      "Полный цикл заказа: оформление покупки и отслеживание статуса заказа в личном кабинете (доступно авторизованным пользователям).",
      "Ролевая модель и Админка: разделение прав доступа (User / Admin) и полноценная админ-панель для управления контентом и заказами.",
      "UX и Кастомизация: поддержка тёмной и светлой темы (Dark / Light Mode) для комфортного взаимодействия.",
      "Full-Stack разработка: проектирование серверной логики, авторизации и самостоятельный UI/UX дизайн интерфейса.",
    ],
    frontend: [
      "Next",
      "Ts",
      "Zustand",
      "Axios",
      "Qs",
      "React Hook Form",
      "Zod",
      "Tailwind",
      "Lucide Icon",
      "Shadcn UI",
      "FSD Архитектура Проекта",
    ],
    backend: ["Next Auth", "Prisma"],
    githubUrl: "https://github.com/Bodich26/next-drivich-v2",
    liveUrl: "https://next-drivich-v2.vercel.app/",
    screenshots: [
      "projects/drivich-v2/1.jpg",
      "projects/drivich-v2/2.jpg",
      "projects/drivich-v2/3.jpg",
      "projects/drivich-v2/4.jpg",
    ],
  },
  {
    id: 3,
    title: "Eternal Abyss",
    subtitle: "Бренд-сайт metal-группы",
    idea: "Создать хаб для фанатов музыкальной группы, который объединяет актуальные релизы, историю, афишу туров и каталог мерча, формируя единый визуальный стиль бренда.",
    implementation: [
      "Типы рендеринга и архитектура Next.js: практическое освоение SSR, SSG и ISR, разграничение Server/Client Components и настройка системы кэширования.",
      "SEO и производительность: полная настройка метаданных, Open Graph и оптимизация загрузки страниц.",
      "Работа с формами: интеграция TanStack Form для обработки и валидации пользовательского ввода.",
      "Админ-панель: UI-интерфейс для управления альбомами, турами и мерчем (Server Actions подготовлены под интеграцию с реальным бэкендом).",
      "UI/UX Дизайн: самостоятельная разработка визуального стиля и интерфейса с нуля под атмосферу группы.",
    ],
    frontend: [
      "Next",
      "Ts",
      "Tanstack Form",
      "Zod",
      "Tailwind",
      "Lucide Icon",
      "FSD Архитектура Проекта",
    ],
    backend: ["Local Data"],
    githubUrl: "https://github.com/Bodich26/next-eternal-abyss",
    liveUrl: "https://next-eternal-abyss.vercel.app/",
    screenshots: [
      "projects/eternal/1.jpg",
      "projects/eternal/2.jpg",
      "projects/eternal/3.jpg",
      "projects/eternal/4.jpg",
    ],
  },
  {
    id: 4,
    title: "Grind Guitar",
    subtitle: "Трекер гитарных практик",
    idea: "Веб-приложение для гитаристов, которое помогает структурировать ежедневные занятия. Проект объединяет необходимые инструменты для практики в одном месте и помогает отслеживать регулярность тренировок, чтобы поддерживать дисциплину.",
    implementation: [
      "Инструменты для занятий: гитарный тюнер, поиск аккордов и таймер практики.",
      "Личная библиотека: формы для добавления собственных упражнений, риффов и техник с отслеживанием выполнения.",
      "Трекинг активности: календарь выполненных дней и динамический расчет серии занятий (стрика).",
      "Профиль и статистика: начисление XP за выполненные задачи, система уровней и учет времени.",
      "Авторизация и синхронизация: вход и регистрация с сохранением данных пользователя в реальном времени.",
    ],
    frontend: [
      "Next",
      "Ts",
      "Tailwind",
      "Zustand",
      "React Hook Form",
      "Zod",
      "ShadCn",
      "Pitchfinder",
      "Chords DB",
      "React Chords",
      "Lucide Icon",
      "FSD Архитектура Проекта",
    ],
    backend: ["Convex", "Better Auth"],
    githubUrl: "https://github.com/Bodich26/next-grind-guitar",
    liveUrl: "https://next-grind-guitar.vercel.app",
    screenshots: [
      "projects/grind-guitar/1.jpg",
      "projects/grind-guitar/2.jpg",
      "projects/grind-guitar/3.jpg",
      "projects/grind-guitar/4.jpg",
    ],
  },
];
